# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 11:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabotapp', '0001_initial'),
    ]


    operations = [
            migrations.CreateModel(
            name='HttpStatusCheck',
            fields=[                
                ('statuscheck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cabotapp.StatusCheck')),],
            options={
                'abstract': False,
            },
            bases=('cabotapp.statuscheck',),
        ),
       
    ]



